export * from './work-detail-details'
export * from './work-detail-header'
export * from './work-detail-solutions'
export * from './work-detail-summary'
export * from './work-lib'
export * from './work.routes'
